// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7_v88esMIyks2cEm6a5kkfLsNJR-kqBI',
    appId: '1:106121594021:android:6d36e099f80dce1224794c',
    messagingSenderId: '106121594021',
    projectId: 'my-first-project-96bcd',
    databaseURL: 'https://my-first-project-96bcd-default-rtdb.firebaseio.com',
    storageBucket: 'my-first-project-96bcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDduq89AZhyhTHmVjaNRAwkEgGHY2QA79Q',
    appId: '1:106121594021:ios:2798adfe950d06ea24794c',
    messagingSenderId: '106121594021',
    projectId: 'my-first-project-96bcd',
    databaseURL: 'https://my-first-project-96bcd-default-rtdb.firebaseio.com',
    storageBucket: 'my-first-project-96bcd.appspot.com',
    iosClientId: '106121594021-1fmr2rnoi69pa2iagdhluk5c3a03k4ok.apps.googleusercontent.com',
    iosBundleId: 'com.example.mydoctor',
  );
}
